import type { ThemeConfig } from '@/types/theme';

export const themeConfigs: ThemeConfig[] = [
  {
    id: 'fresh-schedule',
    name: '清爽日程型',
    tagline: '轻一点，但别糊弄自己。',
    description: '像一张干净日程表，低压力但有边界，适合长期把自己拽回节奏。',
    density: 'calm',
    feedbackStyle: 'schedule',
    recommendedToneId: 'gentle',
    compatibleToneIds: ['gentle', 'warm-companion', 'rational'],
    accentColor: '#0f766e',
    secondaryAccentColor: '#38bdf8',
    dangerColor: '#dc2626',
    successColor: '#16a34a',
    warningColor: '#d97706',
    backgroundColor: '#f5f8f7',
    textColor: '#17201d',
    surfaceColor: '#ffffff',
    surfaceMutedColor: '#e8f1ee',
    mutedTextColor: '#62706a',
    borderColor: '#d9e3de',
    toolbarColor: 'rgba(245, 248, 247, 0.92)',
    tabBarColor: 'rgba(255, 255, 255, 0.96)',
    cardRadius: '8px',
    shadowColor: 'rgba(15, 118, 110, 0.1)',
  },
  {
    id: 'game-achievement',
    name: '游戏成就型',
    tagline: '连击在线，别让进度条断在你手里。',
    description: '更有进度、徽章和完成感，适合用奖励、连击和一点胜负欲推动自己。',
    density: 'playful',
    feedbackStyle: 'achievement',
    recommendedToneId: 'meme',
    compatibleToneIds: ['meme', 'tsundere', 'gentle', 'coach'],
    accentColor: '#2563eb',
    secondaryAccentColor: '#f59e0b',
    dangerColor: '#e11d48',
    successColor: '#22c55e',
    warningColor: '#f59e0b',
    backgroundColor: '#f4f7ff',
    textColor: '#111827',
    surfaceColor: '#ffffff',
    surfaceMutedColor: '#dbeafe',
    mutedTextColor: '#64748b',
    borderColor: '#c7d2fe',
    toolbarColor: 'rgba(244, 247, 255, 0.94)',
    tabBarColor: 'rgba(255, 255, 255, 0.96)',
    cardRadius: '8px',
    shadowColor: 'rgba(37, 99, 235, 0.16)',
  },
  {
    id: 'dark-discipline',
    name: '暗黑纪律型',
    tagline: '少解释，立刻执行。',
    description: '更强对比和风险提示，适合需要压迫感、规则感和一点硬约束的执行状态。',
    density: 'strict',
    feedbackStyle: 'discipline',
    recommendedToneId: 'strict-coach',
    compatibleToneIds: ['strict-coach', 'coach', 'rational', 'adult-command'],
    accentColor: '#ef4444',
    secondaryAccentColor: '#f97316',
    dangerColor: '#f43f5e',
    successColor: '#22c55e',
    warningColor: '#f59e0b',
    backgroundColor: '#101214',
    textColor: '#f5f5f5',
    surfaceColor: '#181b1f',
    surfaceMutedColor: '#2a2f35',
    mutedTextColor: '#a8b0ba',
    borderColor: '#343a42',
    toolbarColor: 'rgba(16, 18, 20, 0.94)',
    tabBarColor: 'rgba(24, 27, 31, 0.96)',
    cardRadius: '8px',
    shadowColor: 'rgba(239, 68, 68, 0.18)',
  },
  {
    id: 'schemer-control',
    name: '腹黑掌控型',
    tagline: '我都看着呢，别想蒙混过去。',
    description: '表面克制，内里有压迫感；适合喜欢被盯住、被拿捏、被拉回规则里的执行状态。',
    density: 'intense',
    feedbackStyle: 'schemer',
    recommendedToneId: 'schemer',
    compatibleToneIds: ['schemer', 'tsundere', 'adult-command', 'strict-coach'],
    accentColor: '#7c3aed',
    secondaryAccentColor: '#10b981',
    dangerColor: '#e11d48',
    successColor: '#22c55e',
    warningColor: '#f59e0b',
    backgroundColor: '#111018',
    textColor: '#f7f3ff',
    surfaceColor: '#1a1724',
    surfaceMutedColor: '#292238',
    mutedTextColor: '#b8aecb',
    borderColor: '#3b3151',
    toolbarColor: 'rgba(17, 16, 24, 0.94)',
    tabBarColor: 'rgba(26, 23, 36, 0.96)',
    cardRadius: '8px',
    shadowColor: 'rgba(124, 58, 237, 0.2)',
  },
  {
    id: 'tsundere-challenge',
    name: '傲娇挑衅型',
    tagline: '才不是鼓励你，是看不下去你摆烂。',
    description: '高饱和、明显挑衅、带一点小剧场感，适合靠嘴硬和胜负欲启动。',
    density: 'playful',
    feedbackStyle: 'challenge',
    recommendedToneId: 'tsundere',
    compatibleToneIds: ['tsundere', 'meme', 'schemer', 'gentle'],
    accentColor: '#db2777',
    secondaryAccentColor: '#06b6d4',
    dangerColor: '#f43f5e',
    successColor: '#14b8a6',
    warningColor: '#f59e0b',
    backgroundColor: '#fff5fb',
    textColor: '#24111d',
    surfaceColor: '#ffffff',
    surfaceMutedColor: '#ffe4f1',
    mutedTextColor: '#79556a',
    borderColor: '#f9a8d4',
    toolbarColor: 'rgba(255, 245, 251, 0.94)',
    tabBarColor: 'rgba(255, 255, 255, 0.96)',
    cardRadius: '8px',
    shadowColor: 'rgba(219, 39, 119, 0.14)',
  },
  {
    id: 'adult-command',
    name: '成人调教型',
    tagline: '规则已经写好，乖乖照做。',
    description: '低饱和深色、命令感和惩戒感更强；适合想把执行权交给规则，被强势拉住节奏的时候。',
    density: 'intense',
    feedbackStyle: 'command',
    recommendedToneId: 'adult-command',
    compatibleToneIds: ['adult-command', 'schemer', 'strict-coach'],
    accentColor: '#b91c1c',
    secondaryAccentColor: '#a16207',
    dangerColor: '#ef4444',
    successColor: '#16a34a',
    warningColor: '#d97706',
    backgroundColor: '#0c0a09',
    textColor: '#faf7f2',
    surfaceColor: '#171312',
    surfaceMutedColor: '#2a211d',
    mutedTextColor: '#c4b7ad',
    borderColor: '#44332c',
    toolbarColor: 'rgba(12, 10, 9, 0.94)',
    tabBarColor: 'rgba(23, 19, 18, 0.96)',
    cardRadius: '8px',
    shadowColor: 'rgba(185, 28, 28, 0.2)',
  },
  {
    id: 'minimal-data',
    name: '极简数据型',
    tagline: '少一点情绪，多一点结果。',
    description: '灰白、低装饰、强调指标和趋势，适合只想看结论、亏欠和下一步的人。',
    density: 'minimal',
    feedbackStyle: 'data',
    recommendedToneId: 'minimal-analyst',
    compatibleToneIds: ['minimal-analyst', 'rational', 'gentle'],
    accentColor: '#334155',
    secondaryAccentColor: '#0f766e',
    dangerColor: '#dc2626',
    successColor: '#15803d',
    warningColor: '#b45309',
    backgroundColor: '#f8fafc',
    textColor: '#0f172a',
    surfaceColor: '#ffffff',
    surfaceMutedColor: '#eef2f7',
    mutedTextColor: '#64748b',
    borderColor: '#d8dee8',
    toolbarColor: 'rgba(248, 250, 252, 0.94)',
    tabBarColor: 'rgba(255, 255, 255, 0.96)',
    cardRadius: '8px',
    shadowColor: 'rgba(15, 23, 42, 0.08)',
  },
];

export const getThemeConfig = (themeId: string) =>
  themeConfigs.find((theme) => theme.id === themeId) ?? themeConfigs[0];
