import type { ThemeConfig } from '@/types/theme';

export const themeConfigs: ThemeConfig[] = [
  {
    id: 'fresh-schedule',
    name: '清爽日程型',
    tagline: '轻一点，但每天都往前。',
    description: '像一张干净日程表，强调稳定、留白和低压力反馈。',
    density: 'calm',
    feedbackStyle: 'schedule',
    accentColor: '#0f766e',
    secondaryAccentColor: '#38bdf8',
    dangerColor: '#dc2626',
    successColor: '#16a34a',
    warningColor: '#d97706',
    backgroundColor: '#f5f8f7',
    textColor: '#17201d',
    surfaceColor: '#ffffff',
    surfaceMutedColor: '#e8f1ee',
    mutedTextColor: '#62706a',
    borderColor: '#d9e3de',
    toolbarColor: 'rgba(245, 248, 247, 0.92)',
    tabBarColor: 'rgba(255, 255, 255, 0.96)',
    cardRadius: '8px',
    shadowColor: 'rgba(15, 118, 110, 0.1)',
  },
  {
    id: 'game-achievement',
    name: '游戏成就型',
    tagline: '连击在线，今天继续升级。',
    description: '更有进度、徽章和完成感，适合奖励驱动的坚持方式。',
    density: 'playful',
    feedbackStyle: 'achievement',
    accentColor: '#2563eb',
    secondaryAccentColor: '#f59e0b',
    dangerColor: '#e11d48',
    successColor: '#22c55e',
    warningColor: '#f59e0b',
    backgroundColor: '#f4f7ff',
    textColor: '#111827',
    surfaceColor: '#ffffff',
    surfaceMutedColor: '#dbeafe',
    mutedTextColor: '#64748b',
    borderColor: '#c7d2fe',
    toolbarColor: 'rgba(244, 247, 255, 0.94)',
    tabBarColor: 'rgba(255, 255, 255, 0.96)',
    cardRadius: '8px',
    shadowColor: 'rgba(37, 99, 235, 0.16)',
  },
  {
    id: 'dark-discipline',
    name: '暗黑纪律型',
    tagline: '少解释，先执行。',
    description: '更强对比和风险提示，适合需要一点压迫感的执行状态。',
    density: 'strict',
    feedbackStyle: 'discipline',
    accentColor: '#ef4444',
    secondaryAccentColor: '#f97316',
    dangerColor: '#f43f5e',
    successColor: '#22c55e',
    warningColor: '#f59e0b',
    backgroundColor: '#101214',
    textColor: '#f5f5f5',
    surfaceColor: '#181b1f',
    surfaceMutedColor: '#2a2f35',
    mutedTextColor: '#a8b0ba',
    borderColor: '#343a42',
    toolbarColor: 'rgba(16, 18, 20, 0.94)',
    tabBarColor: 'rgba(24, 27, 31, 0.96)',
    cardRadius: '8px',
    shadowColor: 'rgba(239, 68, 68, 0.18)',
  },
];

export const getThemeConfig = (themeId: string) =>
  themeConfigs.find((theme) => theme.id === themeId) ?? themeConfigs[0];
