import type { Habit } from '@/types/habit';

export const seedHabits: Habit[] = [
  {
    id: 'sleep-before-midnight',
    name: '23:30 前睡觉',
    reminderTime: '23:00',
    reminderEnabled: true,
    repeatRule: { type: 'daily' },
    rewardText: '连续 7 天做到，周末给自己一段完整放松时间。',
    punishmentText: '今晚少刷 30 分钟短视频。',
    failureThreshold: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'daily-reading',
    name: '看书 20 分钟',
    reminderTime: '21:30',
    reminderEnabled: true,
    repeatRule: { type: 'daily' },
    rewardText: '连续 7 天完成，奖励自己一杯咖啡。',
    punishmentText: '明天补 10 分钟阅读。',
    failureThreshold: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'light-workout',
    name: '轻运动 15 分钟',
    reminderTime: '19:00',
    reminderEnabled: false,
    repeatRule: { type: 'weekdays' },
    rewardText: '连续 30 天完成，买一件喜欢的小东西。',
    punishmentText: '明天补 5 分钟拉伸。',
    failureThreshold: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
